name: Run benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x, 1.20.x, 1.21.x]
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v5.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run bench_test.go
      run: go test -bench=bench_test.go
